[Icon Theme]
Name=DSi
Comment=Nintendo DSi menu style — rounded square icons, plastic, glossy
Inherits=breeze,hicolor
Directories=1080x1080/apps,1080x1080/places,1080x1080/devices,1080x1080/status,1080x1080/actions,scalable/places,scalable/apps,scalable/devices,scalable/mimetypes,scalable/status

[1080x1080/apps]
Size=1080
Type=Fixed
Context=Applications

[1080x1080/places]
Size=1080
Type=Fixed
Context=Places

[1080x1080/devices]
Size=1080
Type=Fixed
Context=Devices

[1080x1080/status]
Size=1080
Type=Fixed
Context=Status

[1080x1080/actions]
Size=1080
Type=Fixed
Context=Actions

[scalable/places]
Size=48
MinSize=16
MaxSize=256
Type=Scalable
Context=Places

[scalable/apps]
Size=48
MinSize=16
MaxSize=256
Type=Scalable
Context=Applications

[scalable/devices]
Size=48
MinSize=16
MaxSize=256
Type=Scalable
Context=Devices

[scalable/mimetypes]
Size=48
MinSize=16
MaxSize=256
Type=Scalable
Context=MimeTypes

[scalable/status]
Size=48
MinSize=16
MaxSize=256
Type=Scalable
Context=Status
